# Generated by Django 5.2.1 on 2025-05-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(help_text='Describe your project in detail')),
                ('link', models.URLField(help_text='Enter the URL to your project')),
                ('technologies_used', models.CharField(help_text='List the technologies used in this project', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('proficiency', models.CharField(help_text='Enter your proficiency level (e.g., Beginner, Intermediate, Advanced)', max_length=60)),
                ('description', models.TextField(help_text='Describe your skill in detail')),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('bio', models.TextField(help_text='Write a short bio about yourself')),
                ('contacts', models.CharField(help_text='Enter your contact information', max_length=60)),
                ('projects', models.ManyToManyField(blank=True, to='core.project')),
                ('skills', models.ManyToManyField(blank=True, to='core.skill')),
            ],
        ),
    ]
